Watching for file changes with StatReloader
[28/Sep/2019 14:43:41] "GET /myplant HTTP/1.1" 200 1865
[28/Sep/2019 14:43:41] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:00:23] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:00:23] "GET /notify/92/ HTTP/1.1" 500 61851
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:00:23] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35112)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:00:33] "GET /notify/25 HTTP/1.1" 301 0
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:00:33] "GET /notify/25/ HTTP/1.1" 500 61851
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:00:33] "GET /notify/25/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35116)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:00:37] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 15:00:37] "GET /static/start.png HTTP/1.1" 200 7934
[28/Sep/2019 15:00:42] "GET /myplant HTTP/1.1" 200 1865
[28/Sep/2019 15:00:42] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 15:00:55] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 15:00:59] "GET /myplant HTTP/1.1" 200 1865
Watching for file changes with StatReloader
[28/Sep/2019 15:03:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:07] "GET /static/smart2.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
[28/Sep/2019 15:03:08] "GET /favicon.ico HTTP/1.1" 404 2529
[28/Sep/2019 15:03:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:03:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:33] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:04:34] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:04:34] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35256)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:04:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:04:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:05:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:06:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:07:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:05] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:08:05] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:08:05] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35292)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:08:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:15] "GET /notify/25 HTTP/1.1" 301 0
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:08:15] "GET /notify/25/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:08:15] "GET /notify/25/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35296)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:08:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:08:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:09:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:30] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:10:30] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:10:30] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35314)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:10:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:10:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:26] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:11:26] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:11:26] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35330)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:11:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:36] "GET /notify/25 HTTP/1.1" 301 0
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:11:36] "GET /notify/25/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:11:36] "GET /notify/25/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35334)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:11:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:48] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:11:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:19] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:12:19] "GET /notify/92/ HTTP/1.1" 500 61863
[28/Sep/2019 15:12:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:29] "GET /notify/25 HTTP/1.1" 301 0
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:12:29] "GET /notify/25/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:12:29] "GET /notify/25/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35354)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:12:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:12:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:13:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:14:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:18] "GET /notify/92 HTTP/1.1" 301 0
[28/Sep/2019 15:15:18] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:15:19] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:15:19] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35382)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:15:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:29] "GET /notify/25 HTTP/1.1" 301 0
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:15:29] "GET /notify/25/ HTTP/1.1" 500 61863
[28/Sep/2019 15:15:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:15:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:16:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:10] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:17:10] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:17:10] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35408)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:17:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:20] "GET /notify/25 HTTP/1.1" 301 0
[28/Sep/2019 15:17:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:25] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:17:26] "GET /notify/25/ HTTP/1.1" 500 61863
[28/Sep/2019 15:17:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:17:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:46] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:18:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:03] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:19:03] "GET /notify/92/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:19:03] "GET /notify/92/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35436)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:19:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:14] "GET /notify/25 HTTP/1.1" 301 0
[28/Sep/2019 15:19:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:17] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:19:19] "GET /notify/25/ HTTP/1.1" 500 61863
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[28/Sep/2019 15:19:19] "GET /notify/25/ HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('223.62.222.246', 35440)
Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 116, in handle_error
    super().handle_error()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "/usr/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 111, in close
    super().close()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[28/Sep/2019 15:19:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:26] "GET /notify2/75 HTTP/1.1" 301 0
Internal Server Error: /notify2/75/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 26, in notify2
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:19:26] "GET /notify2/75/ HTTP/1.1" 500 61886
[28/Sep/2019 15:19:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:48] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:56] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:19:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:41] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 15:20:41] "GET /static/start.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[28/Sep/2019 15:20:41] "GET /favicon.ico HTTP/1.1" 404 2529
[28/Sep/2019 15:20:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:50] "GET /notify/12 HTTP/1.1" 301 0
Internal Server Error: /notify/12/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:20:50] "GET /notify/12/ HTTP/1.1" 500 62513
[28/Sep/2019 15:20:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:55] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 15:20:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:20:58] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:00] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:03] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:05] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:08] "GET /static/smart2.jpg HTTP/1.1" 304 0
Internal Server Error: /notify2/32/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 26, in notify2
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:21:08] "GET /notify2/32/ HTTP/1.1" 500 62536
[28/Sep/2019 15:21:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:10] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:12] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:15] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:17] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:20] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:22] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:25] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:28] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 15:21:28] "GET /myplant HTTP/1.1" 200 1963
----------------------------------------
Exception happened during processing of request from ('223.39.158.196', 43365)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.39.158.196', 61728)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.39.158.196', 39017)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 15:21:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:21:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:22:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:23:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:03] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:24:03] "GET /notify/92/ HTTP/1.1" 500 61863
[28/Sep/2019 15:24:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:13] "GET /notify/25 HTTP/1.1" 301 0
[28/Sep/2019 15:24:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:18] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify/25/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:24:18] "GET /notify/25/ HTTP/1.1" 500 61863
[28/Sep/2019 15:24:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:26] "GET /notify2/75 HTTP/1.1" 301 0
Internal Server Error: /notify2/75/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 26, in notify2
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:24:26] "GET /notify2/75/ HTTP/1.1" 500 61886
[28/Sep/2019 15:24:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:24:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:25:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:48] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:26:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:24] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:27:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:28:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:01] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:29:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:41] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:41] "GET /static/smart2.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
[28/Sep/2019 15:44:41] "GET /favicon.ico HTTP/1.1" 404 2529
[28/Sep/2019 15:44:44] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:50] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify/32/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:44:53] "GET /notify/32/ HTTP/1.1" 500 62512
[28/Sep/2019 15:44:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:44:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:11] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:20] "GET /myplant HTTP/1.1" 200 1963
Internal Server Error: /notify2/18/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 26, in notify2
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 15:45:21] "GET /notify2/18/ HTTP/1.1" 500 62535
[28/Sep/2019 15:45:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 15:45:40] "GET /myplant HTTP/1.1" 200 1963
Invalid HTTP_HOST header: 'ip-172-31-40-36.ap-northeast-2.compute.internal:8080'. You may need to add 'ip-172-31-40-36.ap-northeast-2.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[28/Sep/2019 15:48:15] "GET / HTTP/1.0" 400 59352
Invalid HTTP_HOST header: 'ip-172-31-40-36.ap-northeast-2.compute.internal:8080'. You may need to add 'ip-172-31-40-36.ap-northeast-2.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[28/Sep/2019 15:48:41] "GET / HTTP/1.0" 400 59352
Invalid HTTP_HOST header: 'ip-172-31-40-36.ap-northeast-2.compute.internal:8080'. You may need to add 'ip-172-31-40-36.ap-northeast-2.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[28/Sep/2019 15:50:05] "GET / HTTP/1.0" 400 59352
Invalid HTTP_HOST header: 'ip-172-31-40-36.ap-northeast-2.compute.internal:8080'. You may need to add 'ip-172-31-40-36.ap-northeast-2.compute.internal' to ALLOWED_HOSTS.
Bad Request: /
[28/Sep/2019 15:57:30] "GET / HTTP/1.0" 400 59353
[28/Sep/2019 16:01:03] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 16:13:29] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 16:13:29] "GET /static/start.png HTTP/1.1" 304 0
[28/Sep/2019 16:13:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:13:33] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 16:13:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:13:37] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:13:39] "GET /myplant HTTP/1.1" 200 1963
----------------------------------------
Exception happened during processing of request from ('110.70.54.118', 36289)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 16:13:40] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 16:13:42] "GET /myplant HTTP/1.1" 200 1963
----------------------------------------
Exception happened during processing of request from ('110.70.54.118', 49670)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 16:21:42] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 16:21:45] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:21:47] "GET /myplant HTTP/1.1" 200 1963
----------------------------------------
Exception happened during processing of request from ('110.70.54.118', 17524)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 16:30:40] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 16:30:41] "GET /static/start.png HTTP/1.1" 304 0
[28/Sep/2019 16:35:16] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:16] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 16:35:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:18] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 16:35:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:21] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 16:35:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:23] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:26] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:29] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:31] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:34] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:37] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:37] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:39] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:39] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:43] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:44] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:46] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:46] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:49] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:51] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:54] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:54] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:57] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:35:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:35:59] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:02] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:04] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:07] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:09] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:12] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:15] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:18] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:20] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:23] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:25] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:28] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:31] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:31] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:33] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:36] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:36] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:39] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:39] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:41] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:41] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:44] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:44] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:47] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:49] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:49] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:52] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:55] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:36:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:36:57] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:00] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:03] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:05] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:05] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:08] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:08] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:10] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:13] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:13] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:16] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:18] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:18] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:21] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:21] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:23] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:26] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:26] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:29] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:29] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:32] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:34] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:34] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:37] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:37] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:39] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:39] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:42] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:42] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:44] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:45] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:47] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:50] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:52] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:55] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:37:58] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:37:58] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:00] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:03] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:07] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:07] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:10] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:10] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:12] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:15] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:15] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:17] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:20] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:20] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:23] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:23] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:25] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:28] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:28] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:30] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:33] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:33] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:35] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:36] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:38] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:38] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:42] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:42] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:44] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:45] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:47] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:47] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:50] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:50] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:52] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:52] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:55] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:38:56] "GET /notify/92 HTTP/1.1" 301 0
Internal Server Error: /notify/92/
Traceback (most recent call last):
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/web/webcps/home/views.py", line 17, in notify
    for now in now_status:
TypeError: 'This_status' object is not iterable
[28/Sep/2019 16:38:57] "GET /notify/92/ HTTP/1.1" 500 61863
[28/Sep/2019 16:38:57] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:38:58] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:00] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:00] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:03] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:03] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:06] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:09] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:09] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:12] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:12] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:14] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:14] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:17] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:17] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:19] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:20] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:22] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:22] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:25] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:25] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:27] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:27] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:30] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:30] "GET /static/smart2.jpg HTTP/1.1" 200 5987
[28/Sep/2019 16:39:32] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 16:39:33] "GET /static/smart2.jpg HTTP/1.1" 200 5987
----------------------------------------
Exception happened during processing of request from ('223.38.46.226', 54480)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 17:16:30] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 17:24:45] "GET / HTTP/1.1" 200 1348
[28/Sep/2019 17:24:45] "GET /static/start.png HTTP/1.1" 304 0
[28/Sep/2019 17:24:51] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:24:51] "GET /static/smart2.jpg HTTP/1.1" 304 0
[28/Sep/2019 17:24:53] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:24:55] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:24:57] "GET /myplant HTTP/1.1" 200 1963
----------------------------------------
Exception happened during processing of request from ('110.70.54.118', 46942)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/home/ubuntu/web/myvenv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[28/Sep/2019 17:24:59] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:25:02] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:25:04] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:25:06] "GET /myplant HTTP/1.1" 200 1963
[28/Sep/2019 17:25:08] "GET /myplant HTTP/1.1" 200 1963
